// {% raw -%}Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/orders": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Создание заказа",
                "parameters": [
                    {
                        "description": "OrderCreateRequest Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.OrderCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_OrderResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/orders/item": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Получение заказа по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "order_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_OrderResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "schema.Empty": {
            "type": "object"
        },
        "schema.OrderCreateRequest": {
            "type": "object",
            "properties": {
                "channel_id": {
                    "type": "integer"
                },
                "customer": {
                    "$ref": "#/definitions/schema.OrderCustomer"
                },
                "order_comment": {
                    "type": "string"
                }
            }
        },
        "schema.OrderCustomer": {
            "type": "object",
            "required": [
                "phone"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "schema.OrderResponse": {
            "type": "object",
            "properties": {
                "buyer_id": {
                    "type": "integer"
                },
                "channel_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "order_comment": {
                    "type": "string"
                },
                "order_id": {
                    "type": "integer"
                },
                "order_session": {
                    "type": "string"
                }
            }
        },
        "schema.Response-schema_Empty": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/schema.Empty"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-schema_OrderResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/schema.OrderResponse"
                },
                "status": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`
{%- endraw %}
// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "api-dev.fmobile.kz",
	BasePath:         "/update-templat",
	Schemes:          []string{"https", "http"},
	Title:            "update-templat",
	Description:      "Project short description",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
